export const SCHOOL_DAYS = [
  "Montag",
  "Dienstag",
  "Mittwoch",
  "Donnerstag",
  "Freitag",
]

export const FACH_KUERZEL = {
  B: "Biologie",
  C: "Chemie",
  D: "Deutsch",
  E: "Englisch",
  ETH: "Ethik",
  EKO: "Englisch Konversation",
  EV: "Evangelisch",
  F: "Französisch",
  G: "Geschichte",
  GEO: "Geographie",
  INS: "Informatik",
  K: "Religion",
  INF: "Informatik",
  KU: "Kunst",
  L: "Latein",
  M: "Mathematik",
  MU: "Musik",
  PH: "Physik",
  PUG: "Politik und Gesellschaft",
  RU: "Russisch",
  SMW: "Sport",
  SPKO: "Spanisch Konversation",
  SPS: "Spanisch",
  WR: "Wirtschaft und Recht",
  STB: "Bewegungskünste",
  VKM: "Vertiefungskurs Mathe",
  VOC: "Vokalensemble",
}
